### ISSUE TITLE
Error on installation from Homebrew

### ISSUE THREAD

**Issue by johnmfriend** [vinivendra/homebrew-gryphon#7] opened 2023-03-02 09:31 UTC
error: the library 'GryphonLib' requires macos 10.13, but depends on the product 'SourceKittenFramework' which requires macos 12.0; consider changing the library 'GryphonLib' to require macos 12.0 or later, or the product 'SourceKittenFramework' to require macos 10.13 or earlier.

I'm on 12.6.3. Does the above mean I need to be on the latest version of MacOS? Thanks

**Comment by addie-claudia** [comment] 2023-04-24 20:20
I have the exact same issue, did you ever figure this out?

**Comment by johnmfriend** [comment] 2023-04-25 07:50
I'm afraid not.

**Comment by vinivendra** [comment] 2023-04-27 22:56
Hey folks, we've been working on [supporting Swift 8 and Xcode 14.3 on Gryphon's main repository](https://github.com/vinivendra/Gryphon/issues/127), which probably explains the issue you're having. Feel free to head there to contribute to our efforts or just to catch up on how things are going.

I'm closing this as a duplicate of #8.

**Closed as completed by vinivendra** 2023-04-27 22:56 UTC
